service: twinge-service
frameworkVersion: '3'

custom:
  connectionTableName: 'connection-table-${sls:stage}'
  gamestateTableName: 'gamestate-table-${sls:stage}'

provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ ConnectionTable, Arn ]
            - Fn::GetAtt: [ GamestateTable, Arn ]
  environment:
    CONNECTION_TABLE: ${self:custom.connectionTableName}
    GAMESTATE_TABLE: ${self:custom.gamestateTableName}
  websocketsApiName: twinge-service-websockets
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  connections:
    handler: handlers/connections.handler
    events:
      - websocket:  
          route: $connect
      - websocket:
          route: $disconnect
  default:
    handler: handlers/default.handler
    events: 
      - websocket: $default
  lobby:
    handler: handlers/lobby.handler
    events:
      - websocket:
          route: lobby
          routeResponseSelectionExpression: $default

resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: gamestateId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.connectionTableName}
    GamestateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: gamestateId
            AttributeType: S
        KeySchema:
          - AttributeName: gamestateId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.gamestateTableName}
