service: twinge-service
frameworkVersion: "3"

custom:
  hostname: "twinge-service.mcteamster.com"
  connectionTableName: "connection-table-${sls:stage}"
  gameTableName: "game-table-${sls:stage}"
  apiGatewayServiceProxies:
    - s3:
        path: /
        method: get
        action: GetObject
        bucket:
          Ref: S3Bucket
        key: index.html
        cors: true 

    - s3:
        path: /{myPath+}
        method: get
        action: GetObject
        pathOverride: '{myPath}'
        bucket:
          Ref: S3Bucket
        cors: true       

        requestParameters:
          # if requestParameters has a 'integration.request.path.object' property you should remove the key setting
          'integration.request.path.myPath': 'method.request.path.myPath'
          'integration.request.path.object': 'context.requestId'
          'integration.request.header.cache-control': "'public, max-age=31536000, immutable'"

provider:
  name: aws
  endpointType: regional
  stage: dev
  region: ap-southeast-2
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::Join: ["", [Fn::GetAtt: [ConnectionTable, Arn], "*"]]
            - Fn::Join: ["", [Fn::GetAtt: [GameTable, Arn], "*"]]
  environment:
    CONNECTION_TABLE: ${self:custom.connectionTableName}
    GAME_TABLE: ${self:custom.gameTableName}
    HOSTNAME: ${self:custom.hostname}
  websocketsApiName: twinge-service-websockets
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  connect:
    handler: handlers/connect.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  play:
    handler: handlers/play.handler
    events:
      - websocket:
          route: play
          routeResponseSelectionExpression: $default

resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: gameId
            KeySchema:
              - AttributeName: gameId
                KeyType: "HASH"
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.connectionTableName}
    GameTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
          - AttributeName: roomCode
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: roomCode
            KeySchema:
              - AttributeName: roomCode
                KeyType: "HASH"
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.gameTableName}
    S3Bucket:
      Type: 'AWS::S3::Bucket'

plugins:
  - serverless-apigateway-service-proxy
